### ISSUE TITLE
Data Pre processing module is missing

### ISSUE THREAD

**Issue by say2sarwar** [kagaminccino/LAVSE#2]
The data preprocessing code seems missing from the repo. Can you please upload or send the code to preprocess the whole data?

**Comment by kagaminccino** [comment]
Hi,

We do not release the preprocessing codes because we have difficulty integrating them together.
For the audio data, we use `torchaudio` to convert the waveforms into spectrograms.
For the video data, it gets tricky, so we choose to provide the steps and tools here for you to try.

1) Extract all the frames from the videos.
2) Process each frame with `Dlib` to get the lip images.
3) Use `PIL` to open and resize the lip images, and then convert them to Tensor objects.
4) Compress the tensors by the AE module.
5) Concatenate the AE-compressed tensors in time order for each utterance.
6) Quantize the sequential tensors into the EOFP format by `qtorch` on utterance level.

These are the preprocessing details.
Good luck!

**Comment by kagaminccino** [comment]
Hi,

We do not release the preprocessing codes because we have difficulty integrating them together.
For the audio data, we use `torchaudio` to convert the waveforms into spectrograms.
For the video data, it gets tricky, so we choose to provide the steps and tools here for you to try.

1) Extract all the frames from the videos.
2) Process each frame with `Dlib` to get the lip images.
3) Use `PIL` to open and resize the lip images, and then convert them to Tensor objects.
4) Compress the tensors by the AE module.
5) Concatenate the AE-compressed tensors in time order for each utterance.
6) Quantize the sequential tensors into the EOFP format by `qtorch` on utterance level.

These are the preprocessing details.
Good luck!

**Comment by ashish10alex** [comment]
Hi @kagaminccino , 
Would you please be able to provide/send the source code for visual data pre-processing?
My email - ashish.alex10@gmail.com

**Comment by wubinbai** [comment]
Seriously, giving algorithm is not that explicit as giving codes.
