### ISSUE TITLE
Question about data shape on model output and target data

### ISSUE THREAD

**Issue by hsiaohan0827** [kagaminccino/LAVSE#4]
Hi, 
I found that the shape of the model outputs (including audio and lip) do not contain frame_seq dimension.
Under this condition, how does the loss be calculated due to the shape mismatch on model output and target data?

**Comment by kagaminccino** [comment]
Hi,

No matter how long the `frame_seq` is used, we only predict 1 frame as the output. You can see that in the model forward, all the features of `frame_seq` are flattened and further processed into the dimension of only 1 frame.
The target data is the center frame of the corresponding segment rather than the total length of `frame_seq`. In other words, the loss is obtained frame-wise.
In [the LAVSE system](https://arxiv.org/abs/2005.11769), we use the `frame_seq` of 5 (as the context window described in the [AVDCNN paper](https://arxiv.org/abs/1703.10893)), which means the prediction is the 3rd frame.
By the way, the result spectrogram is obtained by concatenating all of the output frames.
